### ISSUE TITLE
Assignment 05 -- 27 Mar 2024

### ISSUE THREAD

**Issue by dudung** [dudung/nt6094-01-2023-2#8]
+ Learn information on the [slide](https://osf.io/3s7kb).
+ Write you comment below about it, which must include
  - opinion about AI-assisted activities,
  - prediction about the impact when people use AI in excessive way,
  - whether you want to use AI or not,
  - how you will use AI, as an assistance only or as the only source of knowledge or as others (mention them),
  - other aspects you think necessary to add.

**Comment by ririny** [comment]
Based on the information from the slides provided, my opinion is as follows.

The use of activities with the help of AI can provide many benefits and increase efficiency in various activities, one of which is writing journal publications. AI can help in reviewing literature, analyzing data, or even preparing the initial draft of an article. However, this can also be negative if AI is used excessively.

The use of AI can provide excessive dependence, making a person less confident in themselves. Excessive use of AI can also eliminate a person's creativity because they depend too much on AI. The use of AI regarding privacy and security is also uncertain. AI can be a very useful and useful tool if we can use it wisely.

I usually use AI to help with journal writing. I utilize AI to support my journal writing in improving grammar and narrative structure but it is not the only source of knowledge.

Ririn Yulianti
32123003

**Comment by zahraakbari24** [comment]
From the slides of "Journal introduction with AI", I learned about the impact of using AI, which is the discovery of the inaccuracy of scientific journal authors and editors, due to the use of AI tools that greatly facilitate the academic community. For example, AI tools can be used academic writing and the peer review process. My opinion regarding AI-assisted activities is that this has its benefits and challenges, where these tools can greatly increase efficiency and productivity in writing scientific articles, when compared to the process of writing scientific articles a few years ago. However, I think the use of AI tools is very prone to the originality and authenticity of scientific writing. 

The excessive use of AI will lead to the displacement of jobs around the world, as they are replaced by the use of AI technology. In addition, if people become too dependent on AI technology to solve problems and make decisions, this could lead to a decline in human skills and decision-making abilities.

I will continue to use AI, especially in academic learning, because from using some AI tools, I become more effective and faster in understanding scientific theories, faster in understanding the contents of scientific articles, so the learning process becomes more efficient. However, I still have to be careful in using these AI tools, because sometimes the results are inaccurate and incorrect.  
I will use AI as an assistance and one of the sources of knowledge, but not become the only source.

Best regards, 
Zahra Akbari A. (30618001)

**Comment by ayuhanifah** [comment]
According to the slides, in my opinion, AI has both positive and negative effects on researchers. It helps various activities for the researchers, including data analysis, virtual assistance, open chat, reviewing literature, reference merger, etc. However, it also has negative impact on the researchers. When the rely excessively on AI, it may reduce their creativity and abilities to think due to the ease of use of AI. There is a chance that they will publish false data due to the fact that an AI created new theories and conclusions without verifying their validity. The researchers have to aware to the AI’s negative impact.

As a student, I write my papers using AI. In order to improve my writing, I have used paraphrase AI, a reference manager, and a grammar analyzer. Since English is my second language, I requires "someone" to check my grammar. Until now, I prefer not to use an AI as my main source of my knowledge. Although challenging, I still need to explore many papers to expand my knowledge. I might have no urgency for the few information exclude my desiring theory. However, I may require that information in the future.

**Comment by rezaaryanto** [comment]
Technology in the world is developing rapidly, including technology in the academic field. What is currently becoming popular is the use of artificial intelligence (AI), starting with preparation, implementation, and helping to provide final conclusions on research conducted. It is not easy to carry out research at this time. The rapid development of technology means that the demand will be greater to produce better-quality output with the help of technology. 

AI activities must be placed in a position to help researchers, not replace the role of researchers. Human touch is very necessary in conducting research, for example, a sense of engineering, feeling engineering, and rationalizing problems comprehensively. The human touch will be eroded when researchers use AI excessively; limiting the use of AI according to certain corridors will make AI users more optimal in producing research. 

I will use AI technology, which has a helping role, so that the performance and results provided can be optimal. Another aspect that needs to be added is the need to build pride in the originality of the research we carry out while maintaining the human touch.

Reza Aryanto
32123007

**Comment by intansalsabila06** [comment]
Based on my understanding, The use of AI in assisted activities usually useful to help in writing journal. These tools include grammar checks, writing aids and programs that can create written works like essay without human help. On the positive side, AI writing tools such as Grammarly, QuillBot have been found to significantly improve students’ writing skills. These tools utilize advanced algorithms to identify common errors in grammar, punctuation, and syntax and provide suggestions to improve clarity and style. They also offer unique capabilities such as paraphrasing and refining sentences for enhanced effectiveness. In terms of the content and the structure of writing, AI writing tools can significantly enhance the efficiency and quality of writing tasks. AI-based tools, like GPT-3 and its successor GPT-4, have been leveraged to suggest the next word or paragraph in a text, aiding authors in creating human-like compositions
Some prediction the impact of use AI in excessive way. I think, sometimes in my experience, AI writing tools have mixed effect on students to generate ideas that help to provide a starting point when struggling with idea generation. These tools can propose different angles or perspectives in overcoming creative hurdles. 
Based on me, I usually use AI to help me to find some source about the information and keywords for my journal writing. Not only find information but also check the grammar and narrative structure can support the well-structure of my journal writing  

Intan Salsabila
28723006

**Comment by rizalmuhammadramdhan** [comment]
The use of Artificial intelligence as a "Human Assistant" has positive and negative impacts on its use. 
- The positive impacts of using artificial intelligence include increasing productivity, innovation, and efficiency in a job. In this context, artificial intelligence can increase productivity, innovation, and efficiency in writing scientific articles.
- The negative impacts of using Artificial intelligence include dependence on technology, so many replace human jobs, then in the aspect of writing scientific articles can eliminate aspects of originality and frequent ethical violations.

The excessive use of Artificial intelligence will cause humans to depend on technology. This will decrease the "human quality" due to the loss of human ability and creativity in creating a work. and the work created becomes biased and has unclear references.

As a student and technology user, I certainly take advantage of the use of Artificial intelligence, because I realize that I have used Artificial intelligence in helping my work. Such as the use of Mendeley which is an Artificial intelligence in preparing a bibliography and other applications that can help improve the quality of work. However, of course, using artificial intelligence needs to be responsible and pay attention to the ethics and rules that apply.

Artificial intelligence will be positioned as a "discussion partner" in exploring information and knowledge, however, it will not be the only source of knowledge reference.

Rizal Muhammad Ramdhan
28723302

**Comment by ipwardhani** [comment]
Here is my opinion regarding AI-assisted activities.

Using AI as an assistant for an activity is very helpful. AI can help search for and understand learning topics, find solutions, support decision-making, and practice various types of writing, including assisting in writing scientific articles. For academics, especially students, AI is very helpful in writing scientific articles, from creating narratives to editing and proofreading. AI helps the user to review literature and understand the results of data analysis. There are levels of assistance from humans and AI in scientific writing, ranging from spell-checking to substantial editing, which may require publication disclosure. However, when using AI as an assistant becomes excessive, it will impact the users.

AI system users will experience a decline in critical thinking skills and problem-solving abilities when dependent on using AI to solve problems. In addition, excessive use reduces creativity in writing and disrupts social interactions because there is no discussion with humans when solving a problem. It will have an impact on mental health and interpersonal relationships. In the context of journal articles, excessive use of AI can impact ethical issues, the emergence of plagiarism and the author's responsibility for their writing.

For me, AI is very helpful in completing assignments or topics that require more detailed understanding. So, I will use AI as an assistant for certain needs but use it sparingly. For example, when I need to understand a lecture material or research topic, I will search for it using Google and discuss it with LLMs such as ChatGPT, Microsoft Copilot or Gemini. During the discussion, I will always ask for reference sources and directly visit the sites or references (such as journals or books) cited by LLM. Another example: when creating a narrative for an article, I will use AI to help with language or grammar corrections so that the writing becomes more comfortable to read and conforms to the structure.

Issana Pramordha Wardhani
20923002

**Comment by nisaamandar** [comment]
Based on my opinion after reading the information on the slide, AI assists us by providing awareness of what is necessary to act adaptively and quickly solve problems. However, this does not imply that existing technological advancements replace human intelligence and completely rely on programs. Especially in academia, the **use of AI still presents both advantages and disadvantages**. **This aligns with the points raised in the slide, such as how ChatGPT is associated with decreased academic performance and loss of learning memory. Therefore, we need to use AI wisely, not only for the sake of expedited work but also to enhance understanding and originality**.

For me, the use of AI in daily life is cannot ruled out. In academia, AI simplifies tasks like writing by checking language, grammar, and creating highlights from readings. Moreover, **AI serves as a discussion partner**, helping to provide comprehensive thinking on complex issues. **It's important to emphasize that AI is not the sole source of knowledge but rather an assistance only, and its usage requires ethical considerations, nurturing pride in originality, and intelligent application**.

Nisa Amanda Rachmadani (28722301)

**Comment by fhaerannisa** [comment]
Based on the slides, here's my opinion:

AI-assisted activities are highly beneficial in helping us in several ways. We can ask a question, ask for references, ask for DOI for the references, create paragraph with terms and rephrase the previous request into a new request. However, it's important to verify the accuracy of the information provided by AI-assisted activities before relying on it completely since it can make mistakes. Additionally, excessive use of AI can lead to a lack of critical thinking skills and reliance on technology for decision-making. It's essential to maintain a balance between utilizing AI technology and developing one's own critical thinking abilities. However, these are just some potential consequences, and the actual course of what happens will depend on how we develop and use AI. By being aware of these potential risks, we can take steps to minimize them and ensure that AI is used for the benefit of humanity.

I, personally, often use AI-assisted technology to help with various tasks, but I always make sure to double-check the information provided and think critically about the results before making any decisions based on it. It's important to remember that AI should be a helpful assistant, not a replacement for scientific expertise and critical thinking.


Frili Haerannisa Kris
28723301

**Comment by riskaviana20** [comment]
These are my thoughts based on the slides:

Artificial Intelligence (AI) assisted activities have the potential to enhance many parts of our daily life. Tasks can be made more efficient, accurate, and personalized by utilizing AI skills. AI is a useful tool, but we shouldn't depend on it too much and lose the ability to think critically and creatively.

As a student, use AI as a tool rather than a replacement. We should be careful when using AI for certain tasks and think about the moral issues that come up, like privacy, bias, and job displacement. Furthermore, keeping human oversight and control is crucial for ensuring that AI systems align with human values.

AI helps me come up with ideas and make my work easier. AI should be utilized to improve writing talents, not to replace human writers. AI may assist with activities such as reference summarization, error correction, and text reorganization, which is especially beneficial to scientists who are not native English speakers. I utilize AI to find relevant papers, correct grammatical problems, and improve my writing style.

Riskaviana Kurniawati
32123005

**Comment by Fitrayurid** [comment]
Regarding AI-assisted activities, I view it as a mixed blessing, depending on the perspective we take. On one hand, AI represents a significant advancement, offering benefits such as enhanced efficiency, accuracy, and innovation across various sectors, ranging from healthcare to industry. Nevertheless, it's crucial to exercise careful oversight to curb potential misuse and adverse effects of AI utilization.

Relying excessively on AI isn't always advantageous, as it may dull the brain's ability to generate critical and meaningful decisions or ideas once it becomes accustomed to the usual conveniences it offers. As a student, I recognize the immense value of utilizing AI to aid in my studies and research endeavors. Nevertheless, I emphasize the importance of retaining critical thinking skills and a profound grasp of fundamental concepts, I will not solely rely on AI as my primary knowledge source. Striking a balance between technological assistance and human cognitive abilities is paramount.

Furthermore, ethical considerations in both the development and utilization of AI warrant attention. Clear policies and stringent regulations are necessary to ensure responsible AI deployment and its broader societal benefits. Additionally, continual refinement of artificial intelligence to align with human values and mitigate associated risks remains imperative.

Fitra Yurid-28723001

**Comment by christinpalit** [comment]
Based on the slides, here’s my opinion:

Artificial Intelligence (AI) in assisted activity has potential to enhance various aspects in our lives. The presence of AI certainly has advantages and disadvantages for human. The advantages are AI can help humans to solve various complex problems that require effectiveness and efficiency in terms of data and time. In this context, AI can help to increase productivity and effectively in writing scientific articles. But on the other hand, the presence of AI can also pose a great threat to the work done by humans. In this term on writing scientific articles, it can make humans unable to think critically and creatively and become dependent. So, as humans we must be wise in using AI in our daily activities, not use AI in excessive ways.

I, personally, as a student, a lecturer and technology users, will use AI to help with various tasks, one of which is in improving my scientific article writing skills. I am still the one who physically creates the work, making decision on the content and meaning of my work, and the AI is just a tool that supports me in the process. It is important to note that AI does not replace my role, but rather enhances it. 

Christin Palit
32123008

**Comment by syadzaaa** [comment]
What I think about AI-assisted activities, 
AI-assisted activities are generally able to help simplify and speed up daily activities, such as searching for information, creating content, and helping with complex work. The use of AI in scientific journal writing has various advantages and disadvantages. As a student, AI is very helpful in increasing the effectiveness of paper writing such as helping to find information that is difficult to find, creating a reference manager, and being able to summarize several papers. 

Excessive use of AI has adverse effects such as reducing creativity in paper writing and over-reliance to the point of not validating the information. In addition, as long as regulations on the use of AI are not regulated, the quality of scientific paper publications will decrease due to carelessness on the part of the author or even the reviewer. I personally use AI as an aid in finding basic outlines that I will then develop further, correcting grammar, and assisting in writing references. As an AI user, it is necessary to pay attention again and verify whether the information is correct or not. 

Syadza Aisyah Hermadianti
28723007

**Comment by RusdiaSugiana** [comment]
In my view, employing AI to assist in various activities proves immensely beneficial. AI aids in searching for and comprehending learning materials, problem-solving, decision-making, and refining writing skills, including crafting scientific articles. Particularly in academia, especially for students, AI proves invaluable in crafting scholarly pieces, encompassing narrative creation, editing, and proofreading. It facilitates literature review and comprehension of data analysis outcomes. The assistance levels from both humans and AI in scientific writing vary, spanning from basic spell-checking to substantial editing, potentially necessitating disclosure in publications. However, excessive reliance on AI assistance can yield adverse effects.

Personally, I believe that integrating AI into daily life is unavoidable. In academia, AI streamlines tasks such as writing by refining language, grammar, and distilling key insights from literature. Furthermore, AI serves as a collaborative partner, facilitating comprehensive deliberation on intricate subjects. It's crucial to recognize that AI serves as a supplementary tool rather than a sole fount of knowledge. Its usage necessitates ethical considerations, fostering a sense of pride in originality, and prudent application.

Rusdia Shaleha Sugiana
28723003

**Comment by iirrkkhaamm** [comment]
Based on the powerpoint that has been presented, my view regarding AI which has recently been widely used in helping human activities is certainly a very positive thing. With the role of AI, we are facilitated in our activities. We often start to be presented with various AI to help our activities.  This shows the development of human civilization, especially in the field of technology. Of course, the presence of AI has many positive impacts.

However, unfortunately this is also proportional to the negative impact that is also caused. AI that is used excessively will make us someone who is more spoiled. The dependence caused by excessive use of AI can reduce our abilities and skills, because everything is provided instantly. It can even result in the reduction of our brain intelligence. 

So, as an academic (student) the use of AI can be very helpful, but it is still necessary to pay attention to the limits. Therefore, I will use AI but in accordance with predetermined limits. The use of AI is certainly not the only source of knowledge, but only as a companion role. This means that when we read an article or book that is incomplete, we can use the role of AI to complete the reading, so that the knowledge we learn is broader. Another aspect that needs to be added is related to ethics. Don't because of the convenience provided, all the things we should do ourselves are instead assisted by AI. In conclusion, I strongly support the use of AI but taking into account ethics, and its limitations.

Fariz Irkham Muadhif - 28723005

**Comment by dindactr** [comment]
Dari presentasi "Pengenalan AI dalam Jurnal", saya mendapatkan pemahaman tentang implikasi penggunaan AI, yang memperlihatkan kemajuan dalam proses penulisan dan penyuntingan jurnal ilmiah, meskipun terdapat keraguan terkait dengan keotentikan karya akademis akibat penggunaan alat AI. Contoh yang disebutkan adalah penggunaan AI dalam penulisan artikel dan proses peer review. Menurut saya, pemanfaatan AI dalam kegiatan akademis memiliki keunggulan dan tantangan; meskipun dapat meningkatkan efisiensi dan produktivitas, namun juga memunculkan risiko terhadap orisinalitas dan keaslian tulisan ilmiah.  

Jika ketergantungan pada teknologi AI terus meningkat, kemungkinan besar akan terjadi pergeseran dalam pasar kerja secara global, dengan pekerjaan manusia digantikan oleh AI. Lebih lanjut, penggunaan berlebihan AI dalam pengambilan keputusan dapat mengakibatkan penurunan kemampuan manusia dalam membuat keputusan dan pemecahan masalah.  

Secara pribadi, saya tetap memanfaatkan AI terutama dalam konteks pembelajaran akademis, karena AI dapat menunjukkan bahwa penggunaan beberapa alat AI dapat meningkatkan efisiensi dalam memahami teori ilmiah dan menyerap informasi dari artikel ilmiah. Namun, saya hanya menggunakan AI sebagai alat bantu dan tambahan sumber pengetahuan dan tetap memeriksa informasi yang diberikan dengan sumber lain dan melakukan penilaian kritis terhadap hasilnya dan relevan dengan informasi yang saya inginka.

Salam Hormat
Dinda Citra Utami (20923006)

**Comment by merrydj** [comment]
The use of AI provides us with convenience and time efficiency in many aspects of our lives. AI can perform tasks as instructed, helping to enhance human productivity across various fields. However, excessive use of AI can have negative effects. Overreliance on AI can lead humans to lose the ability to think critically, creatively, and lose intuition, which are essential elements in problem-solving and innovation.

While AI is a useful tool for humans, it is highly recommended not to rely solely on AI. Human oversight is needed to ensure the ethical and responsible use of AI. Furthermore, excessive use of AI can lead to social issues such as job displacement due to being replaced by AI.

AI is a tool that is very useful for complementing human capabilities rather than replacing humans entirely. I believe that using AI as an assistant can help me improve my abilities in utilizing skills and knowledge. However, I will not rely solely on AI as my source of knowledge. It is essential to balance the use of AI and my own intellectual abilities as a human. I will use AI as a tool to assist me.

Best Regards, 
Merry 
28723304

**Comment by petalflows** [comment]
Based on the slide, here's my opinion about AI-assisted activities

The use of AI in learning and research activities has a significant positive impact, especially for academics. AI can assist in searching for and understanding learning topics, as well as supporting the process of writing academic papers from creating narratives to peer review processes. AI also facilitates literature review and understanding of data analysis results, with various levels of assistance from humans and AI in the academic writing process.

However, it should be noted that excessive use of AI can have negative effects, both individually and globally. Individuals who rely too much on AI may experience a decrease in critical thinking skills and become overly dependent on technology. Additionally, widespread use of AI also has the potential to replace human jobs globally.

As a student, I will use AI as a discussion companion to assist in the learning process, especially in understanding complex learning materials. However, I will also pay attention to the limits of AI usage to avoid reducing critical thinking skills and independence in learning.

Best Regards,
Siti Bunga Rohiyatun Nufus
20923010

**Comment by nuralifiah** [comment]
Based on the slide, here's my opinion about AI activities

I believe that AI-assisted activities have great potential to increase efficiency and productivity in various fields. AI can help automate routine tasks, provide faster and more accurate data analysis, and assist in better decision-making.

However, if people use AI excessively, I predict that this could cause several negative impacts. One of them is excessive dependence on technology, which can reduce people's ability to think critically and solve problems independently. In addition, uncontrolled use of AI can lead to privacy and data security issues.

Personally, I want to use AI because I see many benefits it offers. However, I will use AI as an assistant only, not as the sole source of knowledge. I believe that AI should be used to complement human abilities, not replace them.

I will use AI for tasks such as data analysis, process automation, and research. However, I will still rely on human knowledge and experience in making final decisions.

Moreover, it is important to consider ethical aspects in the use of AI. We must ensure that AI is used responsibly and does not harm others. Training and education about the use of AI are also important so that society can utilize this technology wisely.

Best Regards,
Nur Alifiah
20923007

**Comment by rikepradila** [comment]
The use of AI in journal writing and editing has a significant impact on efficiency and productivity. AI can help automate routine tasks such as grammar checks, formatting, and even providing data-driven suggestions for improvements. However, despite the advancements AI offers in these processes, there are legitimate concerns regarding the authenticity and originality of academic works produced with AI assistance. Over-reliance on AI in these activities can blur the line between human-generated work and machine-assisted output, ultimately undermining academic credibility.

The excessive use of AI can have far-reaching impacts. If dependency on this technology continues to grow, the global job market could experience a significant shift, with many human jobs being replaced by AI. Moreover, over-reliance on AI for decision-making can weaken human critical thinking and problem-solving skills, as people rely more on algorithms than on intuition and experience.

Personally, I want to use AI because of the many benefits it offers, particularly in enhancing work efficiency and productivity. However, I will use AI as a tool, not as the sole source of knowledge. AI should complement human abilities, not replace them. I will use AI for tasks such as data analysis, process automation, and research, but the final decisions will still be based on human knowledge and experience.

Another important aspect to consider is the ethics of using AI. We must ensure that AI is used responsibly and does not harm others. This includes protecting data privacy and security and ensuring transparency in how AI is used. Training and education on AI usage are also crucial so that society can use this technology wisely and effectively. Additionally, clear regulations and policies supporting ethical AI usage should be developed and implemented to prevent the misuse of this technology.

Best regards,
Rike Pradila (20923012)

**Comment by agnesindrwt** [comment]
The integration of AI in scientific journal writing offers significant benefits, such as enhancing data analysis, improving language precision, and streamlining the peer review process. However, over-reliance on AI could stifle creativity, diminish the diversity of perspectives, and lead to homogenized research outputs. Personally, I would use AI as an assistive tool rather than the sole source of knowledge, leveraging it for tasks like literature review, editing, and preliminary data analysis while ensuring human insight drives the core research and writing. This balanced approach maintains the integrity and originality of scientific inquiry, preserving the rigor and creativity essential to scientific progress, while benefiting from AI's efficiency and accuracy.

Best Regards, 
Agnes Indarwati Susanto (20923013)
